version: 2.1
jobs:
  build:
    docker:
     - image: circleci/node:12.8.1-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Execute Unit Tests
          command: yarn test
